name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install CA Certificates
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall ca-certificates
        sudo update-ca-certificates
    
    - name: Update pymongo
      run: python -m pip install --upgrade pymongo

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      env: 
        MONGODB_URI: "mongodb+srv://myappuser:Mongoatlas@cluster0.gas37.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&ssl=false"
      run: python -m unittest discover -s tests
