# name: Python CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
    
#     - name: Update pymongo
#       run: python -m pip install --upgrade pymongo

#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.13'

#     - name: Install dependenciess
#       run: |
#         pip install pymongo[srv]  # Add this line to ensure SRV support
#         pip install certifi      # Add this for SSL certificates
#         pip install -r requirements.txt

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run Unit Tests
#       env: 
#         MONGODB_URI: "mongodb+srv://myappuser:Mongoatlas@cluster0.gas37.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=60000&socketTimeoutMS=60000&ssl=false"
#       run: python -m unittest discover -s tests




name: Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python Environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Unit Tests
    - name: Run tests
      env:
        MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      run: |
        pytest tests/

